package acl

import "slices"
var Permissions = []string{
	"Package.Read",
	"Package.Delete",
	"Package.Edit",
	"Package.Create",
	"Plan.Read",
	"Plan.Delete",
	"Plan.Edit",
	"Plan.Create",
	"Client.Read",
	"Client.Delete",
	"Client.Edit",
	"Client.Create",
	"Member.Read",
	"Member.Delete",
	"Member.Create",
	"ClientLog.Read",
	"ClientLog.Delete",
	"ClientLog.Edit",
	"ClientLog.Create",
	"MembershipPlan.Read",
	"MembershipPlan.Delete",
	"MembershipPlan.Edit",
	"MembershipPlan.Create",
	"MembershipRequest.Read",
	"MembershipRequest.Edit",
	"PackageRequest.Read",
	"PackageRequest.Edit",
	"PackageRequest.Create",
	"Coach.Read",
	"Coach.Delete",
	"Coach.Edit",
	"Coach.Create",
	"WorkoutCategory.Read",
	"WorkoutCategory.Edit",
	"WorkoutCategory.Create",
	"WorkoutCategory.Delete",
	"Workout.Read",
	"Workout.Delete",
	"Workout.Edit",
	"Workout.Create",
	"Inventory.Read",
	"Inventory.Edit",
	"Inventory.Delete",
	"Inventory.Create",
	"Staff.Edit",
	"Staff.Create",
	"Staff.Read",
	"Staff.Delete",
	"Role.Read",
	"Role.Edit",
	"Role.Delete",
	"Role.Create",
	"TimeSlot.Read",
	"TimeSlot.Edit",
	"TimeSlot.Delete",
	"TimeSlot.Create",
	"DateSlot.Read",
	"DateSlot.Delete",
	"DateSlot.Edit",
	"DateSlot.Create",
	"Reservation.Read",
	"Reservation.Edit",
	"Payment.Read",
	"Penalty.Read",
	"Penalty.Edit",
	"Report.Read",
	"Report.Create",
	"Message.Read",
	"CoachLog.Read",
	"CoachLog.Edit",
	"CoachLog.Create",
	"CoachLog.Delete",
}


func HasPermission(requiredPermission string, permissions []string) bool {
		return slices.Contains(permissions, requiredPermission)
}