CREATE TABLE IF NOT EXISTS equipments(
 id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) DEFAULT '',
 model VARCHAR(100) DEFAULT '',
 quantity INT DEFAULT 0,
 cost_price DECIMAL(13, 2) NOT NULL,
 date_received DATE NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)