CREATE TABLE IF NOT EXISTS coach_schedule(
     id INT NOT NULL PRIMARY KEY,
    `date` DATE NOT NULL,
    `time` TIME NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
)